name: expandable_bottom_sheet
description: This is a BottomSheet with a draggable height like the Google Maps App on Android.
version: 1.1.1+1
repository: https://github.com/torbenkeller/expandable_bottom_sheet
issue_tracker: https://github.com/torbenkeller/expandable_bottom_sheet/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter:
